apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: qdr-topo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: qdr-topo
    spec:
      containers:
      - name: qdr-topo
        image: quay.io/ernieallen/qdr-topo
        ports:
          - name: http
            containerPort: 8000
        resources:
          requests:
            memory: 256Mi
            cpu: "0.1"
          limits:
            memory: 256Mi
            cpu: "0.5"
---
apiVersion: v1
kind: Service
metadata:
  name: qdr-topo
  labels:
    name: qdr-topo
spec:
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: http
  selector:
    name: qdr-topo
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    name: qdr-topo
  name: qdr-topo
  namespace: myproject
spec:
  host: qdr-topo-myproject.127.0.0.1.nip.io
  port:
    targetPort: http
  to:
    kind: Service
    name: qdr-topo
    weight: 100
  wildcardPolicy: None
